Repository Nullify-Platform/Logger, pull requests merged in 2024-03, with the labels that each got.

#54 update to go1.20 and update ci to use github actions instead of containers
  .github/workflows/ci-go.yml
  .golangci.yml
  cmd/main.go
  go.mod
  pkg/logger/configure.go
  pkg/logger/fields.go
  pkg/logger/globals.go
  pkg/logger/http.go
  pkg/logger/logger.go
  pkg/logger/options.go
  renovate.json
  tests/with_options_test.go
Labels: minor

#52 feat: add tracing and error collection
  README.md
  cmd/main.go
  go.mod
  go.sum
  pkg/logger/configure.go
  pkg/logger/globals.go
  pkg/logger/http.go
  pkg/logger/logger.go
  pkg/logger/middleware/logger.go
  pkg/logger/tracer/sns.go
  pkg/logger/tracer/sqs.go
  pkg/logger/tracer/tracer.go
  tests/add_field_test.go
  tests/development_test.go
  tests/production_test.go
  tests/with_options_test.go
Labels: enhancement, major

#57 chore: rename function to `F()`
  README.md
  cmd/main.go
  pkg/logger/globals.go
  pkg/logger/http.go
  pkg/logger/middleware/logger.go
  tests/add_field_test.go
  tests/development_test.go
  tests/production_test.go
  tests/with_options_test.go
Labels: minor

#59 feat(trace): add ssm fetch support
  README.md
  go.mod
  go.sum
  pkg/logger/configure.go
Labels: patch
