Repository Nullify-Platform/Logger, pull requests merged in 2024-07, with the labels that each got.

#76 add jonathan to codeowners
  .github/CODEOWNERS
Labels: no-release

#78 add generic custom trace header carrier
  pkg/logger/tracer/custom.go
Labels: minor

#79 remove all panics and fatals
  cmd/main.go
  pkg/logger/configure.go
  pkg/logger/logger.go
  pkg/logger/middleware/logger.go
Labels: minor

#80 change flush errors to warnings
  pkg/logger/logger.go
Labels: patch

#81 add trace propagation unit tests
  pkg/logger/tracer/custom_test.go
  pkg/logger/tracer/sqs_test.go
Labels: no-release

#83 NUL-899-glitchtip-event-enrichment
  go.mod
  go.sum
  pkg/logger/configure.go
  pkg/logger/logger.go
  pkg/logger/logger_test.go
Labels: minor

#84 add more sentry tags
  pkg/logger/configure.go
Labels: minor

#86 fixed sentry "mechanism type required" error
  go.mod
  pkg/logger/configure.go
  pkg/logger/logger_test.go
Labels: patch

#87 AddECSTagsToSentryEvents
  go.mod
  go.sum
  pkg/logger/configure.go
  pkg/logger/globals.go
  pkg/logger/logger.go
  pkg/logger/logger_test.go
Labels: patch

#88 export tags to env for python apps
  pkg/logger/configure.go
Labels: patch

#89 silently fail if AWS_LAMBDA_FUNCTION_NAME is empty
  pkg/logger/configure.go
Labels: patch

#90 no-op if SENTRY_DSN not defined
  pkg/logger/configure.go
Labels: patch

#91 add a function to copy a tracer from an old context to a new context
  pkg/logger/tracer/tracer.go
Labels: minor

#92 add function to copy the logger from an old to new context
  pkg/logger/globals.go
  pkg/logger/tracer/tracer.go
Labels: minor
