Repository Nullify-Platform/Logger, pull requests merged in 2025-01, with the labels that each got.

#116 add record error to the logger package
  pkg/logger/logger.go
Labels: minor

#117 reduce the renovate bot updates interval and make it less noisy
  renovate.json
Labels: no-release

#119 add more logging to logger
  pkg/logger/fields.go
  pkg/logger/fields_test.go
Labels: minor

#120 Adding Trace-ID
  pkg/logger/fields.go
Labels: minor

#122 add tracer middleware
  pkg/logger/middleware/logger.go
  pkg/logger/middleware/tracer.go
  pkg/logger/tracer/custom.go
  pkg/logger/tracer/custom_test.go
  pkg/logger/tracer/headers.go
Labels: minor

#124 fix tracer middleware
  pkg/logger/middleware/tracer.go
Labels: patch

#123 Adding more struct to use reflect fields for optional logging
  cmd/main.go
  pkg/logger/logger.go
  pkg/logger/nullify_context.go
Labels: minor

#125 add more fields for rebel base
  pkg/logger/nullify_context.go
Labels: minor

#126 add full file path to caller
  pkg/logger/configure.go
  tests/production_test.go
Labels: patch

#127 add struct based logic for the logger package
  pkg/logger/configure.go
  pkg/logger/logger.go
  pkg/logger/nullify_context.go
Labels: minor
